// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MoneyGroup.WebApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OrderDetailedDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The buyerId property</summary>
        public int? BuyerId { get; set; }
        /// <summary>The buyerName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BuyerName { get; set; }
#nullable restore
#else
        public string BuyerName { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The participants property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MoneyGroup.WebApi.Models.ParticipantDetailedDto>? Participants { get; set; }
#nullable restore
#else
        public List<global::MoneyGroup.WebApi.Models.ParticipantDetailedDto> Participants { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The total property</summary>
        public double? Total { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MoneyGroup.WebApi.Models.OrderDetailedDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MoneyGroup.WebApi.Models.OrderDetailedDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::MoneyGroup.WebApi.Models.OrderDetailedDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "buyerId", n => { BuyerId = n.GetIntValue(); } },
                { "buyerName", n => { BuyerName = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "participants", n => { Participants = n.GetCollectionOfObjectValues<global::MoneyGroup.WebApi.Models.ParticipantDetailedDto>(global::MoneyGroup.WebApi.Models.ParticipantDetailedDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "total", n => { Total = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("buyerId", BuyerId);
            writer.WriteStringValue("buyerName", BuyerName);
            writer.WriteStringValue("description", Description);
            writer.WriteIntValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::MoneyGroup.WebApi.Models.ParticipantDetailedDto>("participants", Participants);
            writer.WriteStringValue("title", Title);
            writer.WriteDoubleValue("total", Total);
        }
    }
}
#pragma warning restore CS0618
