// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MoneyGroup.WebApi.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PaginationModelOfOrderDetailedDto : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The count property</summary>
        public int? Count { get; set; }
        /// <summary>The items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MoneyGroup.WebApi.Models.OrderDetailedDto>? Items { get; set; }
#nullable restore
#else
        public List<global::MoneyGroup.WebApi.Models.OrderDetailedDto> Items { get; set; }
#endif
        /// <summary>The page property</summary>
        public int? Page { get; set; }
        /// <summary>The total property</summary>
        public int? Total { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MoneyGroup.WebApi.Models.PaginationModelOfOrderDetailedDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MoneyGroup.WebApi.Models.PaginationModelOfOrderDetailedDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::MoneyGroup.WebApi.Models.PaginationModelOfOrderDetailedDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "count", n => { Count = n.GetIntValue(); } },
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::MoneyGroup.WebApi.Models.OrderDetailedDto>(global::MoneyGroup.WebApi.Models.OrderDetailedDto.CreateFromDiscriminatorValue)?.AsList(); } },
                { "page", n => { Page = n.GetIntValue(); } },
                { "total", n => { Total = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("count", Count);
            writer.WriteCollectionOfObjectValues<global::MoneyGroup.WebApi.Models.OrderDetailedDto>("items", Items);
            writer.WriteIntValue("page", Page);
            writer.WriteIntValue("total", Total);
        }
    }
}
#pragma warning restore CS0618
